method-invocation-spec:
  test-loop-count: 10
  invocation-interval: 5000
  device-id:
    - test-device-method-1
  device-method-name: TestMethod
  data-size-of-payload: 1000
  sleep-msec-in-method: 1000
  data-size-of-response: 1000
