method-invocation-spec:
  test-loop-count: 10
  invocation-interval: 5000
  # Specify test device set
  # 'device-id' specify list of test device by DeviceId
  device-id:
    - test-direct-method-edge-1
  # 'device-type' specify test devices by marked in reported property
  device-type: method-invocation-test-device
  method-name: TestMethod
  module-id: TestMethodModule
  data-size-of-payload: 1000
  sleep-msec-in-method: 1000
  data-size-of-response: 1000
  response-timeout: 30000
